### ISSUE TITLE
Timer for the Poll

### ISSUE THREAD

**Issue by echoi2** [cs130-w22/Group-A2#16]
## User Story
As a **user**, I would like **the polls to be able to time out** so that **situations where someone forgetting to vote or choosing not to vote will still allow all the other votes to be considered and used to determine majority to keep the night moving**.

## Detailed Description
 Timer for the poll.

## Acceptance Criteria
- [ ] Given **that an allotted amount of time has passed after opening a poll**, then **the poll should automatically close and just use the existing votes to determine majority to keep the night moving**.

**Comment by seijiotsu** [comment]
We ended up implementing this differently; the Leader chooses the final bars manually.
