### ISSUE TITLE
Notification System to Alert the Group of Decisions

### ISSUE THREAD

**Issue by echoi2** [cs130-w22/Group-A2#22]
## User Story
As a **user**, I would like **to be notified about changes in group schedules** so that **I know where I am going tonight**.

## Detailed Description
Send notification to users when changes are made to the schedule.

## Acceptance Criteria
- [ ] Given **an option to enable app notifications**, then **user should be able to receive notifications about changes in group schedule.**

**Comment by seijiotsu** [comment]
This is a front-end thing. The front-end should continuously poll the back end for the group schedule and then detect when it changes. Then notify the user.

**Comment by seijiotsu** [comment]
We no longer implement it this way.
