### ISSUE TITLE
Connection to Uber API for Traveling

### ISSUE THREAD

**Issue by echoi2** [cs130-w22/Group-A2#23]
## User Story
As a **user**, I would like **to book an uber for my transportation** so that **I can commute hassle-free**.

## Detailed Description
Allow users to view uber prices and the option to book them.

## Acceptance Criteria
- [ ] Given **an option to view/book uber**, then **users should be able to view/book an uber from their current position to the next bar/home.**

**Comment by seijiotsu** [comment]
Out of scope because Uber no longer allows access to their API.
