### ISSUE TITLE
Notification System for Departure Time alerts

### ISSUE THREAD

**Issue by echoi2** [cs130-w22/Group-A2#25]
## User Story
As a **user**, I would like **to get departure time alerts for my public transit/cab** so that **I don't miss it**.

## Detailed Description
Notification system for departure time alerts.

## Acceptance Criteria
- [ ] Given **an option to enable app notifications**, then **user should be able to receive time alert notifications for his/her public transit/cab rides.**

**Comment by seijiotsu** [comment]
Out of scope. May revisit in the future.
