### ISSUE TITLE
Poll to Declare Leader

### ISSUE THREAD

**Issue by echoi2** [cs130-w22/Group-A2#4]
## User Story
As a **user**, I would like **to vote in the poll for the leader** so that **someone whom I trust can plan the outing**.

## Detailed Description
Provide an option in the group view to vote in the poll to select the leader. 

## Acceptance Criteria
- [ ] Given **a poll for leader selection**, then **the members of the bar crawl app group should be able to select one leader for the group by majority vote.**

**Comment by seijiotsu** [comment]
We ended up implementing this differently, with Group Codes.
